name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set version for release
        run: echo "RELEASEVER=$(echo v0.1)" >> $GITHUB_ENV

    - name: Install winget
      uses: Cyberboss/install-winget@v1

    - name: Install Windows ADK, Windows MDT and Cargo
      shell: powershell
      run: |
        winget install --id Microsoft.WindowsADK --disable-interactivity --accept-source-agreements
        winget install --id Microsoft.ADKPEAddon --disable-interactivity --accept-source-agreements
        winget install --id Rustlang.Rustup --disable-interactivity --accept-source-agreements

    - name: Build amd64 image
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\DandISetEnv.bat"
        copype amd64 c:\winpe-amd64

    - name: Mount amd64 image
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\DandISetEnv.bat"
        Dism /Mount-Image /ImageFile:"c:\winpe-amd64\media\sources\boot.wim" /index:1 /MountDir:"c:\winpe-amd64\mount"

    - name: Copy vcruntime140.dll into image
      shell: powershell
      run: |
        cp C:\Windows\System32\vcruntime140.dll C:\winpe-amd64\mount\Windows\System32\vcruntime140.dll

    - name: Compile TMaze
      shell: powershell
      run: |
        git clone https://github.com/ur-fault/TMaze.git
        cd TMaze
        cargo build --release -F hashbrown --no-default-features

    - name: Copy TMaze into image
      shell: powershell
      run: |
        cp .\TMaze\target\release\tmaze.exe C:\winpe-amd64\mount\tmaze.exe

    - name: Unmount amd64 image
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\DandISetEnv.bat"
        Dism /Unmount-Image /MountDir:c:\winpe-amd64\mount /Commit

    - name: Build amd64 iso
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\DandISetEnv.bat"
        MakeWinPEMedia /ISO c:\winpe-amd64 c:\winpe-amd64\Windows-TMaze-Edition.iso

    - name: Create new release
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create --draft --tag ${{ env.RELEASEVER }}

    - name: Upload iso to release
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.RELEASEVER }} c:\winpe-amd64\Windows-TMaze-Edition.iso

    - name: Upload wim file to release
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.RELEASEVER }} c:\winpe-amd64\media\sources\boot.wim